/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2006
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 *
 * Filename:
 * ---------
 * attdb.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 * Low Energy Attribute Protocol database header
 *
 * Author:
 * -------
 * Autumn Li(mtk01174)
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * $Log$
 *
 * 08 01 2011 autumn.li
 * [ALPS00064244] [BT] [BLE] ATT/GATT revision
 * ATT/GATT revision
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef __ATTDB_H
#define __ATTDB_H

#define BT_ATT_BASE_RECORD_HANDLE 0x0001

#if defined(__BT_4_0_PRIVACY__) && defined(__BT_LE_STANDALONE__)
#define ATT_RECORD_NO_GAP   5
#else
#define ATT_RECORD_NO_GAP   9
#endif
#ifdef __GATT_SERVICE_CHANGED_CHARACTERISTIC_SUPPORT__
#define ATT_RECORD_NO_GATT  3
#else
#define ATT_RECORD_NO_GATT  0
#endif

#if defined(__BT_PRXR_PROFILE__) || defined(__BT_PRXM_PROFILE__)
#define ATT_RECORD_NO_PROXIMITY  9
#else
#define ATT_RECORD_NO_PROXIMITY  0
#endif

#define ATT_MAX_RECORD (ATT_RECORD_NO_PROXIMITY + ATT_RECORD_NO_GAP + ATT_RECORD_NO_GATT)

#define ATT_MAX_GROUP_RECORD 5


typedef enum
{
    /* GAP handle start */
    ATT_HANDLE_PRIMARY_SERVICE_GAP = BT_ATT_BASE_RECORD_HANDLE,
#if defined(__BT_4_0_PRIVACY__) && defined(__BT_LE_STANDALONE__)
    ATT_HANDLE_GAP_CHARACTERISTIC_PERIPHERAL_PRIVACY,
    ATT_HANDLE_GAP_CHARACTERISTIC_PERIPHERAL_PRIVACY_VALUE,
#ifdef __BT_4_0_PRIVACY_RECON_ADDR__
    ATT_HANDLE_GAP_CHARACTERISTIC_RECONNECT_ADDRESS,
    ATT_HANDLE_GAP_CHARACTERISTIC_RECONNECT_ADDRESS_VALUE,
#endif
#endif
    ATT_HANDLE_GAP_CHARACTERISTIC_DEVICE_NAME,
    ATT_HANDLE_GAP_CHARACTERISTIC_DEVICE_NAME_VALUE,
    ATT_HANDLE_GAP_CHARACTERISTIC_APPEARANCE,
    ATT_HANDLE_GAP_CHARACTERISTIC_APPEARANCE_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_GAP_END = ATT_HANDLE_GAP_CHARACTERISTIC_APPEARANCE_VALUE,
    /* GAP handle end */

    /* GATT handle start */
#ifdef __GATT_SERVICE_CHANGED_CHARACTERISTIC_SUPPORT__
    ATT_HANDLE_PRIMARY_SERVICE_GATT,
    ATT_HANDLE_GATT_CHARACTERISTIC_SERVICE_CHANGED,
    ATT_HANDLE_GATT_CHARACTERISTIC_SERVICE_CHANGED_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_GATT_END = ATT_HANDLE_GATT_CHARACTERISTIC_SERVICE_CHANGED_VALUE,
#endif
    /* GATT handle end */

    /* Proximity handle start */
#if defined(__BT_PRXR_PROFILE__) || defined(__BT_PRXM_PROFILE__)
    ATT_HANDLE_PRIMARY_SERVICE_IMMEDIATE_ALERT,
    ATT_HANDLE_IA_CHARACTERISTIC_ALERT_LEVEL,
    ATT_HANDLE_IA_CHARACTERISTIC_ALERT_LEVEL_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_IMMEDIATE_ALERT_END = ATT_HANDLE_IA_CHARACTERISTIC_ALERT_LEVEL_VALUE,

    ATT_HANDLE_PRIMARY_SERVICE_TX_POWER,
    ATT_HANDLE_TP_CHARACTERISTIC_TX_POWER_LEVEL,
    ATT_HANDLE_TP_CHARACTERISTIC_TX_POWER_LEVEL_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_TX_POWER_END = ATT_HANDLE_TP_CHARACTERISTIC_TX_POWER_LEVEL_VALUE,

    ATT_HANDLE_PRIMARY_SERVICE_LINK_LOSS,
    ATT_HANDLE_LL_CHARACTERISTIC_ALERT_LEVEL,
    ATT_HANDLE_LL_CHARACTERISTIC_ALERT_LEVEL_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_LINK_LOSS_END = ATT_HANDLE_LL_CHARACTERISTIC_ALERT_LEVEL_VALUE,
#endif
    /* Proximity handle end */

#if defined(__BT_TIMEC_PROFILE__) || defined(__BT_TIMES_PROFILE__)
    ATT_HANDLE_PRIMARY_SERVICE_CURRENT_TIME,
    ATT_HANDLE_CHARACTERISTIC_CT_TIME,
    ATT_HANDLE_CHARACTERISTIC_CT_TIME_VALUE,
    ATT_HANDLE_CLIENT_CHARACTERISTIC_CONFIG_CT_TIME_VALUE,
    ATT_HANDLE_CHARACTERISTIC_LOCAL_TIME_INFO,
    ATT_HANDLE_CHARACTERISTIC_LOCAL_TIME_INFO_VALUE,
    ATT_HANDLE_CHARACTERISTIC_REF_TIME_INFO,
    ATT_HANDLE_CHARACTERISTIC_REF_TIME_INFO_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_CURRENT_TIME_END = ATT_HANDLE_CHARACTERISTIC_REF_TIME_INFO_VALUE,

    ATT_HANDLE_PRIMARY_SERVICE_NEXT_DST_CHANGE,
    ATT_HANDLE_CHARACTERISTIC_TIME_WITH_DST,
    ATT_HANDLE_CHARACTERISTIC_TIME_WITH_DST_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_NEXT_DST_CHANGE_END = ATT_HANDLE_CHARACTERISTIC_TIME_WITH_DST_VALUE,

    ATT_HANDLE_PRIMARY_SERVICE_REFERENCE_TIME_UPDATE,
    ATT_HANDLE_CHARACTERISTIC_TIME_UPDATE_CONTROL_POINT,
    ATT_HANDLE_CHARACTERISTIC_TIME_UPDATE_CONTROL_POINT_VALUE,
    ATT_HANDLE_CHARACTERISTIC_TIME_UPDATE_STATE,
    ATT_HANDLE_CHARACTERISTIC_TIME_UPDATE_STATE_VALUE,
    ATT_HANDLE_PRIMARY_SERVICE_REFERENCE_TIME_UPDATE_END = ATT_HANDLE_CHARACTERISTIC_TIME_UPDATE_STATE_VALUE,
#endif
} bt_att_main_record_handle;


#endif
