
#ifndef __BT_SDAP_TESTER_MESSAGE_H__
#define __BT_SDAP_TESTER_MESSAGE_H__

	MSG_ID_BT_SDAP_TESTER_CMD = MSG_ID_BT_SDAP_TESTER_GROUP_START,
	MSG_ID_BT_SDAP_TESTER_GROUP_END,

#endif // __BT_SDAP_TESTER_MESSAGE_H__
