#ifndef __BT_HDP_MESSAGE_H__
#define __BT_HDP_MESSAGE_H__

#ifdef SOURCE_INSIGHT_TRACE
typedef enum 
{
#endif

    MSG_ID_BT_HDP_ACTIVATE_REQ = MSG_ID_BT_HDP_GROUP_START,
    MSG_ID_BT_HDP_ACTIVATE_CNF,
    MSG_ID_BT_HDP_DEACTIVATE_REQ,
    MSG_ID_BT_HDP_DEACTIVATE_CNF,    
    MSG_ID_BT_HDP_REGISTER_INSTANCE_REQ,
    MSG_ID_BT_HDP_REGISTER_INSTANCE_CNF,
    MSG_ID_BT_HDP_DEREGISTER_INSTANCE_REQ,
    MSG_ID_BT_HDP_DEREGISTER_INSTANCE_CNF,
    
    MSG_ID_BT_HDP_CONNECT_REQ,    
    MSG_ID_BT_HDP_CONNECT_CNF,  
    MSG_ID_BT_HDP_DISCONNECT_REQ,
    MSG_ID_BT_HDP_DISCONNECT_CNF,
    MSG_ID_BT_HDP_REMOVE_CONNECTION_REQ,
    MSG_ID_BT_HDP_REMOVE_CONNECTION_CNF,
    MSG_ID_BT_HDP_CHANNEL_OPENED_IND, 
    MSG_ID_BT_HDP_CHANNEL_CLOSED_IND, 
    
    MSG_ID_BT_HDP_GET_MAIN_CHANNEL_REQ, 
    MSG_ID_BT_HDP_GET_MAIN_CHANNEL_CNF,      
    MSG_ID_BT_HDP_GET_INSTANCE_REQ, 
    MSG_ID_BT_HDP_GET_INSTANCE_CNF,  
    MSG_ID_BT_HDP_GET_L2CAP_CHANNEL_REQ, 
    MSG_ID_BT_HDP_GET_L2CAP_CHANNEL_CNF,      
    
	MSG_ID_BT_HDP_ECHO_REQ,
	MSG_ID_BT_HDP_ECHO_CNF,
	
	MSG_ID_BT_HDP_RECONNECT_REQ,
	
    MSG_ID_BT_HDP_GROUP_END,

#ifdef SOURCE_INSIGHT_TRACE
};
#endif

#endif

